# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or
# pull request events but only for the main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run
# sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    # Steps represent a sequence of tasks that will be executed as
    # part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your
      # job can access it
      - uses: actions/checkout@v2

      - name: 'Set up Python 3.8'
        uses: actions/setup-python@v2
        with:
          # Semantic version range syntax or exact version of a Python
          # version.
          python-version: '3.8'

      - name: 'Install pipenv'
        run: pip install pipenv

      - name: 'Install zip and unzip'
        run: sudo apt-get install -y zip unzip

      - name: 'Setup Rust'
        uses: actions/checkout@v2

      - name: 'Install pandoc'
        run: sudo apt-get install -y pandoc

      - name: 'Install packages'
        run: sudo apt install gdebi-core wget

      - name: 'Download latest chrome'
        run: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

      - name: 'Install chrome'
        run: sudo gdebi google-chrome-stable_current_amd64.deb

      - name: 'Setup pipenv'
        # This is also done in the Makefile but i broke it
        # here for visibility.
        run: pipenv install -d

      - name: 'Make setup'
        # Builds the wabt tools needed for the build.
        # It is actually part of the build but was
        # broken out here to make the steps a bit shorter.
        run: make setup

      - name: 'Make build'
        run: make

      - name: 'Make Test'
        run: make test

      - name: 'Make webapp'
        run: make webapp

      - name: 'Upload webapp'
        uses: actions/upload-artifact@v2
        with:
          name: 'qspm.zip'
          path: webapp/qspm.zip
          # Maximum is 90 days for public repos.
          retention-days: 30
